server:
  port: 8080
spring:
  application:
    name: Assistant
  r2dbc:
    url: r2dbc:pool:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
    username: postgres.fapeflbyihcviewrjreu
    password: ClaudeAIProject2024

